addons:
  ssh_known_hosts: 34.243.147.82
sudo: required
dist: trusty
language: node_js
node_js:
- '8.0'
cache:
  directories:
  - node_modules
before_install:
  - bash .scripts/install.sh
install:
- npm install
before_script:
- export CI=false
after_script:
- bash .scripts/deploy.sh
notifications:
  slack: ohtupartio:9Fqci61YwcZE8Wj25AzaV2ID
