sudo: required
dist: trusty
language: node_js
node_js:
  - '11.10.1'
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts: 18.197.93.24
before_install:
  - bash .scripts/install.sh
install:
  - npm install
before_script:
  - export CI=false
after_script:
  - bash .scripts/deploy.sh
notifications:
  slack: ohtupartio:9Fqci61YwcZE8Wj25AzaV2ID
env:
  global:
    - REACT_APP_GOOGLE_LOGIN_TOKEN=1059818174105-9p207ggii6rt2mld491mdbhqfvor2poc.apps.googleusercontent.com
