---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export CI=false
notifications:
    slack: ohtupartio:9Fqci61YwcZE8Wj25AzaV2ID
